name: Use the Composite Action with Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate list using Markdown 1
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY

      - name: Do anything elsee
        run: echo teest 1
        
      - name: Generate list using Markdown 2
        run: |
          echo "- Lets add a second bullet point" > $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
        

      # Uses the Composite Action
      - name: Build and Push the image
        uses: pampamzi/composite@main
        with:
          registry_username: ${{secrets.REGISTRY_USERNAME}}
          registry_password: ${{secrets.REGISTRY_PASSWORD}}
          image_name: my-awesome-app
          tag: $GITHUB_RUN_NUMBER
